name: TLPProject
channels:
  - conda-forge
  - defaults
dependencies:
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - click=8.1.7
  - colorama=0.4.6
  - exceptiongroup=1.2.0
  - flask=3.1.0
  - iniconfig=1.1.1
  - intel-openmp=2024.2.1
  - itsdangerous=2.2.0
  - joblib=1.4.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.6
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libsqlite=3.49.1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.6
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - mkl=2024.2.2
  - numpy=2.0.2
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - pip=25.0.1
  - pluggy=1.5.0
  - pytest=8.0.0
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.11
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - setuptools=75.8.0
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.0.1
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - werkzeug=3.1.3
  - wheel=0.45.1
  - pip:
      - aiofiles==24.1.0
      - dict-toolbox==5.0.0
      - jinja2==3.1.4
      - lazy-object-proxy==1.10.0
      - msgpack==1.1.0
      - nest-asyncio==1.6.0
      - pop==27.1.0
      - pop-config==12.0.4
      - pop-loop==1.1.0
      - pydevd==3.3.0
      - python-dotenv==0.21.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - rend==7.0.2
      - six==1.16.0
      - sniffio==1.3.1
      - toml==0.10.2
      - tzdata==2024.2
prefix: C:\Users\klm97849\Anaconda3\envs\TLPProject
